### ISSUE TITLE
Better GUI design

### ISSUE THREAD

**Issue by chronofanz** [chronofanz/EnhancedDistrictServices#13]
Need bigger fonts at minimum.
Should also replicate the look and feel of other world info panels in the game, with a close button.
Also, we should use the dropdown box from the Industries Panel rather using our own.

**Comment by t1a2l** [comment]
@chronofanz  - Maybe use the DIstrict 3 mod gui instead

**Comment by chronofanz** [comment]
Eh, I'll mark this wontfix.  GUI is good enough, but if somebody else decides to rework the GUI, that would be fine by me.
