### ISSUE TITLE
Taxi and taxi stand issue

### ISSUE THREAD

**Issue by t1a2l** [chronofanz/EnhancedDistrictServices#26]
@chronofanz  - Hey, since the latest update taxis try to park in the taxi stand but fails and then try again and again (infinite loop of trying). Also no one seems to use taxis at all only few, It is very wierd. If a person wants to use a taxi from his district to go to another one can he use it? Does the taxi only response to calls inside the district to an area inside the district?

**Comment by chronofanz** [comment]
Fixed in v 1.0.14
